<?php
/**
 * Implements hook_block_info().
 */
function registered_users_count_block_info() {
$blocks['registered_users_count'] = array(
    'info' => t('Registered users counter'),
  );
  return $blocks;
}

/**
 * Implements hook_block_view().
 */
function registered_users_count_block_view($delta = '') {
  $members = db_query("SELECT count(uid) FROM {users}")->fetchField();
  $block = array();
  switch ($delta) {
    case 'syndicate':
      $block['content'] = t("There are !member_nr registered users", array('!member_nr' => $members));
  break;
  }
  return $block;
}
